const COLORS = {
  BACKGROUND_COLOR_PRIMARY: '#504992',
  BACKGROUND_COLOR_SECONDARY: '#6058AF',
  BACKGROUND_COLOR_SHADE: '#CDCBEF',
  YELLOW_SHADE: '#FFD15C',
  MAGENTA_SHADE: '#F3705A',
  GREEN_SHADE: '#62C9CC',
  WHITE: '#FFFFFF',
  BLACK: '#000000',
};

export default COLORS;
