import COLORS from '../Common/Colors';

const style = {
  icon: {
    width: 28,
    height: 13,
  },
  background: {
    ios: {
      flex: 1,
      width: '100%',
      marginTop: '-56%',
      marginBottom: '-56%',
      top: 0,
      left: 0,
    },
    android: {
      flex: 1,
      width: '100%',
      // marginTop: '-35%',
      // marginBottom: '-35%',
      marginTop: '-65%',
      marginBottom: '-65%',
    },
  },
  infoOverlay: {
    position: 'absolute',
    // borderColor: 'red',
    // borderStyle: 'solid',
    // borderWidth: 1,
    width: '100%',
    height: '100%',
  },
  sectionOne: {
    // borderColor: 'black',
    // borderStyle: 'solid',
    // borderWidth: 1,
    width: '100%',
    height: '25%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTwo: {
    // borderColor: 'green',
    // borderStyle: 'solid',
    // borderWidth: 1,
    width: '100%',
    height: '25%',
  },
  sectionThree: {
    // borderColor: 'purple',
    // borderStyle: 'solid',
    // borderWidth: 1,
    width: '100%',
    height: '25%',
  },
  sectionFour: {
    // borderColor: 'yellow',
    // borderStyle: 'solid',
    // borderWidth: 1,
    width: '100%',
    height: '25%',
  },
  sectionNumberLabelContainer: {
    backgroundColor: COLORS.MAGENTA_SHADE,
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'black',
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  sectionLabel: {
    color: COLORS.WHITE,
    textAlign: 'center',
  },
  sectionAssessmentInfo: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    marginLeft: '-8%',
  },
  sectionLabelContainer: {
    backgroundColor: COLORS.BACKGROUND_COLOR_SECONDARY,
    borderRadius: 5,
    width: 135,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTwoParent: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  sectionTwoItemContainer: {
    backgroundColor: COLORS.BACKGROUND_COLOR_SECONDARY,
    flexDirection: 'row',
    padding: 15,
    borderRadius: 5,
    width: 200,
    marginTop: '17%',
    marginLeft: '-10%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  sectionTwoImageContainer: {
    width: 50,
    height: 50,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  sectionTwoImage: {
    width: 35,
    height: 35,
  },
  sectionTwoLabel: {
    fontSize: 12,
    fontWeight: '300',
    textAlign: 'center',
    color: COLORS.WHITE,
  },
  sectionTwoNumericLabel: {
    backgroundColor: COLORS.MAGENTA_SHADE,
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'black',
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '15%',
  },
  sectionProfessionals: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    // alignContent: 'flex-end',
    marginRight: '13%',
  },
  sectionProfessionalsImage: {
    ios: {
      width: 125,
      height: 125,
      marginTop: '-15%',
      marginRight: '15%',
    },
    android: {
      width: 100,
      height: 100,
      marginTop: '-5%',
      marginRight: '15%',
    },
  },
  sectionJourneyProfessionalsImageContainer: {
    // borderColor: 'purple',
    // borderStyle: 'solid',
    // borderWidth: 1,
    // justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  sectionJourneyLaunchImageContainer: {
    // borderColor: 'purple',
    // borderStyle: 'solid',
    // borderWidth: 1,
    alignItems: 'center',
  },
  sectionLaunchImage: {
    width: 175,
    height: 175,
    marginLeft: '-15%',
  },
  sectionLaunch: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: '-8%',
  },
  sectionLaunchLabelContainer: {
    backgroundColor: COLORS.BACKGROUND_COLOR_SECONDARY,
    borderRadius: 5,
    width: 135,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionLaunchNumberLabelContainer: {
    backgroundColor: COLORS.MAGENTA_SHADE,
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'black',
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '8%',
  },
};

export default style;

// {
//   borderColor: 'red',
//     borderStyle: 'solid',
//   borderWidth: 1,
// }
